<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test" nsURI="http://fr.ubo.mde.test" nsPrefix="test">
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//N">
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" upperBound="-1" eType="#//test2/B"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="N" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="test2" nsURI="http://fr.ubo.mde.test2" nsPrefix="test2">
    <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//N">
      <eAnnotations source="comments" references="#//test2/B/%comments%"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nb" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="42"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nb2" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="42" derived="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
