<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml2" nsURI="http://www.eclipse.org/uml2/2.1.0/UML2" nsPrefix="uml2">
  <eClassifiers xsi:type="ecore:EClass" name="Classe" eSuperTypes="//N">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eleves" upperBound="-1" eType="//test2/B" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="N" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="n" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="test2" nsURI="http://fr.ubo.mde.test2" nsPrefix="test2">
    <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="//N">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nb" lowerBound="1" defaultValueLiteral="42">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nb2" lowerBound="1" defaultValueLiteral="42" derived="true">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
